---
title: "p8105_hw3_bp2678"
author: "Brady Pham"
date: 2023-10-12
output: github_document
---
```{r}
library(tidyverse)
library(dplyr)
library(moderndive)
```

#QUESTION 2 
```{r}
library(p8105.datasets)
data("brfss_smart2010")

```

```{r}
brfss_smart2010_df = brfss_smart2010 |>
  janitor::clean_names() |>
  rename(States = locationabbr,
          County = locationdesc) |>
  filter(response %in% c("Excellent", "Very Good", "Good", "Fair", "Poor")) |>
  filter(topic == "Overall Health") |>
  mutate(
    response = factor(response, levels = c("Poor", "Fair", "Good", "Very Good", "Excellent"),
                      ordered = TRUE)) |>
  arrange(response)

```

I renamed the variables like locationabbr to "States" and locationdesc to "County". I also
organized the responses from poor to excellent where poor starts first. Addtionally, I filter
the responses in topic where it is "overall health".

```{r}
newdataset_2002 <- 
  brfss_smart2010_df |>  
  filter(year == "2002")

answer_2002 <- newdataset_2002 |> 
  count(States) |>  
  filter(n >= 7)
answer_2002
```

There are 36 states that were visted more than 7 times in 2002

```{r}
newdataset_2010 <- 
  brfss_smart2010_df |>  
  filter(year == "2010")

answer_2010 <- newdataset_2010 |> 
  count(States) |>  
  filter(n >= 7)
answer_2010

```

There are 45 states that were visted more than 7 times in 2010


